config/routes.rb
Rails.application.routes.draw do
  root to: 'feeds#index'
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :favorites, only: [:index]
  end
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :image, presence: true
  has_many :feeds, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_feeds, through: :favorites, source: :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_user, only: [:index]
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_url, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り解除しました"
  end
  def index
    @favorites = Favorite.where(user_id: @user.id)
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    render :new if @feed.invalid?
  end
  def edit
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @feed.save
        ContactMailer.contact_mail(@feed).deliver
        redirect_to feeds_path, notice: "投稿を作成しました！"
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def authenticate_user
    @current_user = User.find_by(id: session[:user_id])
    if @current_user == nil
      flash[:notice] = "ログインが必要です。"
      redirect_to new_session_path
    end
  end

  def correct_user
     if current_user.id != @feed.user_id
       flash[:notice] = "権限がないです"
       redirect_to feeds_path
     end
  end

  def feed_params
    params.require(:feed).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :correct_user, only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @feeds = Feed.where(user_id: @user.id)
    if @user != current_user
      flash[:notice] = "権限がないです"
      redirect_to feeds_path
    end
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "権限がないです"
      redirect_to feeds_path
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    # redirect_to(show_users_url) unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>
<div class="container">

    <ul class="row">
      <li class="col-xs-3">Title</li>
      <li class="col-xs-3">Content</li>
      <li class="col-xs-3">Contributor</li>
    </ul>


   <% unless @favorites.empty? %>
    <% @favorites.each do |favorite| %>
    <ul class="row">
        <li class="col-xs-3"><%= favorite.feed.title %></li>
        <li class="col-xs-3"><%= favorite.feed.content %></li>
        <li class="col-xs-3"><%= image_tag favorite.feed.image.url %></li>
        <li class="col-xs-3"><%= favorite.user.name %></li>
        <li class="col-xs-3"><%= image_tag favorite.user.image.url %></li>
    </ul>
    <% end %>
    <% else %>
    <%= "このユーザはお気に入りした物がありません" %>
  <% end %>

app/views/feeds/_form.html.erb
<%= form_with(model: @feed, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @feed.title %></p>
  <p>本文:<%= @feed.content %></p>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>
<div class="container">

    <ul class="row">
      <li class="col-xs-3">Title</li>
      <li class="col-xs-3">Content</li>
      <li class="col-xs-3">Contributor</li>
    </ul>



    <% @feeds.each do |feed| %>
    <ul class="row">
        <li class="col-xs-3"><%= feed.title %></li>
        <li class="col-xs-3"><%= feed.content %></li>

        <li class="col-xs-3"><%= feed.user.name %></li>

        <li class="col-xs-1"><%= link_to 'Show', feed %></li>
      <% if feed.user_id == current_user.id %>
        <li class="col-xs-1"><%= link_to 'Edit', edit_feed_path(feed) %></li>
        <li class="col-xs-1"><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
    <% end %>

</div>
<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>

<p>
<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</p>

<p>
<% if @feed.user_id == current_user.id %>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footvisual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><a href="/feeds">
          <%= image_tag 'vintage.jpg', size: '150x108'%>
        </a></li>
      </ul>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit "Edit my account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @user.image.url %>
</p>
<p>
<%= link_to 'Favorites', user_favorites_path(@user) %>
</p>
<% if @user == current_user %>
<%= link_to 'Edit', edit_user_path(@user) %>
<% end %>